### PR TITLE
Design the Post Details page

### PR DESCRIPTION
**Pull request by ekakshjanweja**
Created UI Of Post Details Page: Post Detail Page is named as campus_ola_five.dart

### CODE REVIEW

**Comment by Hareesh-Nandigrama** [comment]
Remove all the firebase files and commit again

**Comment by Hareesh-Nandigrama** [comment]
Instead of static data in your UI, try to pass the post model and display data from that model in the post detail screen. Apart from that great job with the UI

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama On it.

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama I updated the screen but I was not able to understand the getNote thing. Sorry!

**Comment by Hareesh-Nandigrama** [comment]
getNote? @ekakshjanweja

**Comment by Hareesh-Nandigrama** [comment]
@ekakshjanweja Don't pass all the arguments to the CampusOlaFive, you need to define CampusOlaFive  class that takes a single argument of the type post model and using this post model you need to extract data in the post detail page

**Comment by ekakshjanweja** [comment]
Yeah I got that I will try to work on it tomorrow after college 😊

**Comment by Hareesh-Nandigrama** [comment]
@ekakshjanweja You can use just push instead

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama You can check it now I complete It

**Comment by Hareesh-Nandigrama** [comment]
Closes #20

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama Will this reflect on my hacktoberfest profile?

**Comment by Hareesh-Nandigrama** [comment]
@ekakshjanweja yes

**Pull request merged**
